[versions]

assertj = "3.27.6"
controlsfx = "11.0.3"
dependencyAnalysis-gradlePlugin = "3.5.1"
equalsverifier = "4.0.2"
javafx = "23.0.2"
jetbrains-annotations = "26.0.2"
junit = "6.0.1"
jvmDependencyConflictResolution-gradlePlugin = "2.4"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
mockk = "1.14.3"
osDetector-gradlePlugin = "1.7.3"
slf4j = "2.0.17"
testfx = "4.0.18"
testfx-monocle = "21.0.2"
versionsCheck-gradlePlugin = "0.53.0"

[libraries]

[libraries.assertj]
module = "org.assertj:assertj-core"
version.ref = "assertj"

[libraries.controlsfx]
module = "org.controlsfx:controlsfx"
version.ref = "controlsfx"

[libraries.dependencyAnalysis-gradlePluginDependency]
module = "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin"
version.ref = "dependencyAnalysis-gradlePlugin"

[libraries.equalsverifier]
module = "nl.jqno.equalsverifier:equalsverifier"
version.ref = "equalsverifier"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.jvmDependencyConflictResolution-gradlePluginDependency]
module = "org.gradlex:jvm-dependency-conflict-resolution"
version.ref = "jvmDependencyConflictResolution-gradlePlugin"

[libraries.javafx-base]
module = "org.openjfx:javafx-base"
version.ref = "javafx"

[libraries.javafx-controls]
module = "org.openjfx:javafx-controls"
version.ref = "javafx"

[libraries.javafx-fxml]
module = "org.openjfx:javafx-fxml"
version.ref = "javafx"

[libraries.javafx-graphics]
module = "org.openjfx:javafx-graphics"
version.ref = "javafx"

[libraries.javafx-media]
module = "org.openjfx:javafx-media"
version.ref = "javafx"

[libraries.javafx-swing]
module = "org.openjfx:javafx-swing"
version.ref = "javafx"

[libraries.javafx-web]
module = "org.openjfx:javafx-web"
version.ref = "javafx"

[libraries.junit-api]
module = "org.junit.jupiter:junit-jupiter-api"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit"

[libraries.kotlin-gradlePluginDependency]
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"
version.ref = "kotlinx-coroutines"

[libraries.mockk]
module = "io.mockk:mockk"
version.ref = "mockk"

[libraries.mockk-dsl-jvm]
module = "io.mockk:mockk-dsl-jvm"
version.ref = "mockk"

[libraries.osDetector-gradlePluginDependency]
module = "com.google.gradle:osdetector-gradle-plugin"
version.ref = "osDetector-gradlePlugin"

[libraries.slf4j-simple]
module = "org.slf4j:slf4j-simple"
version.ref = "slf4j"

[libraries.testfx-core]
module = "org.testfx:testfx-core"
version.ref = "testfx"

[libraries.testfx-junit5]
module = "org.testfx:testfx-junit5"
version.ref = "testfx"

[libraries.testfx-monocle]
module = "org.testfx:openjfx-monocle"
version.ref = "testfx-monocle"

[bundles]

javafx = [
	"javafx-base",
	"javafx-controls",
	"javafx-fxml",
	"javafx-graphics",
	"javafx-media",
	"javafx-swing",
	"javafx-web"
]

kotlinx-coroutines-jvm = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm"
]

mockk-jvm = ["mockk", "mockk-dsl-jvm"]

testfx = ["testfx-core", "testfx-junit5", "testfx-monocle"]

[plugins]

[plugins.dependencyAnalysis-gradlePlugin]
id = "com.autonomousapps.dependency-analysis"
version.ref = "dependencyAnalysis-gradlePlugin"

[plugins.jvmDependencyConflictDetection-gradlePlugin]
id = "org.gradlex.jvm-dependency-conflict-detection"
version.ref = "jvmDependencyConflictResolution-gradlePlugin"

[plugins.jvmDependencyConflictResolution-gradlePlugin]
id = "org.gradlex.jvm-dependency-conflict-resolution"
version.ref = "jvmDependencyConflictResolution-gradlePlugin"

[plugins.kotlin-gradlePlugin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.versionsCheck-gradlePlugin]
id = "com.github.ben-manes.versions"
version.ref = "versionsCheck-gradlePlugin"
